
-- candidates

insert into candidates (name,code,sex) values ('Frances Johnson Morris Allison','FRJAL','F');
insert into candidates (name,code,sex) values ('Dwolu Murvee Anderson Sr.','DWMAN','M');
insert into candidates (name,code,sex) values ('Gbatokai F.M. Dakinah','GBFDA','M');
insert into candidates (name,code,sex) values ('Michael Abou Jones','MIAJO','M');
insert into candidates (name,code,sex) values ('Duannah A. Kamara','DUAKA','M');
insert into candidates (name,code,sex) values ('Lahai Gbabye Lansanah','LAGLA','M');
insert into candidates (name,code,sex) values ('Abraham Abraham Nyei','ABANY','M');
insert into candidates (name,code,sex) values ('Morris Gato Saytumah','MOGSA','M');
insert into candidates (name,code,sex) values ('Neh Dukuly Tolbert','NEDTO','F');
insert into candidates (name,code,sex) values ('Hajah Sheri Washington','HASWA','F');
insert into candidates (name,code,sex) values ('Numehn Owen Dunbar','NUODU','M');
insert into candidates (name,code,sex) values ('Augustus Jonathan Flomo','AUJFL','M');
insert into candidates (name,code,sex) values ('James Yarkpawolo Gbarbea Jr.','JAYGB','M');
insert into candidates (name,code,sex) values ('Jefferson Gbaryan','JEGBA','M');
insert into candidates (name,code,sex) values ('Jewel C. Howard-Taylor','JECHO','F');
insert into candidates (name,code,sex) values ('Ranney Banama Jackson','RABJA','M');
insert into candidates (name,code,sex) values ('Edwin Tokpa Juah','EDTJU','M');
insert into candidates (name,code,sex) values ('Martin Fahnlon Kerkula Sr.','MAFKE','M');
insert into candidates (name,code,sex) values ('Mator M.F. Kpangbai','MAMKP','M');
insert into candidates (name,code,sex) values ('Benedict Kpakama Sagbeh','BEKSA','M');
insert into candidates (name,code,sex) values ('James Karpee Saybay','JAKSA','M');
insert into candidates (name,code,sex) values ('Franklin Obed Siakor','FROSI','M');
insert into candidates (name,code,sex) values ('Henrique Flomo Tokpa','HEFTO','M');
insert into candidates (name,code,sex) values ('Siokin Civicus Barsi-Giah','SICBA','M');
insert into candidates (name,code,sex) values ('Gbehzohngar Milton Findley','GBMFI','M');
insert into candidates (name,code,sex) values ('Jonathan Lambort Kaipay','JOLKA','M');
insert into candidates (name,code,sex) values ('Solomon James Murray','SOJMU','M');
insert into candidates (name,code,sex) values ('Gabriel B Smith','GABSM','M');
insert into candidates (name,code,sex) values ('Elizabeth G.M. Armstrong','ELGAR','F');
insert into candidates (name,code,sex) values ('Matthew V.Z. Darblo Sr.','MAVDA','M');
insert into candidates (name,code,sex) values ('Henrietta Victoria Kandakai','HEVKA','F');
insert into candidates (name,code,sex) values ('Fodee Kromah','FOKRO','M');
insert into candidates (name,code,sex) values ('Abel Momodu Massalay','ABMMA','M');
insert into candidates (name,code,sex) values ('James Kormah Momo','JAKMO','M');
insert into candidates (name,code,sex) values ('Jesse Zinnah Segbo','JEZSE','M');
insert into candidates (name,code,sex) values ('Varney Gbotonambi Sherman','VAGSH','M');
insert into candidates (name,code,sex) values ('Simeon Boima Taylor','SIBTA','M');
insert into candidates (name,code,sex) values ('Mohammed Abraham Ware Sr.','MOAWA','M');
insert into candidates (name,code,sex) values ('Victor Varney Watson','VIVWA','M');
insert into candidates (name,code,sex) values ('Sumoward Edwin Harris','SUEHA','M');
insert into candidates (name,code,sex) values ('Gertrude Tene Lamin','GETLA','F');
insert into candidates (name,code,sex) values ('Nathaniel Farlo McGill','NAFMC','M');
insert into candidates (name,code,sex) values ('J.S.B. Theodore Momo Jr.','JSTMO','M');
insert into candidates (name,code,sex) values ('Daniel Flomo Naatehn Sr.','DAFNA','M');
insert into candidates (name,code,sex) values ('Alaric K. Tokpa','ALKTO','M');
insert into candidates (name,code,sex) values ('Fatuma Mamie Zinnah','FAMZI','F');
insert into candidates (name,code,sex) values ('George Saigbe Boley Sr.','GESBO','M');
insert into candidates (name,code,sex) values ('Charles Gaye Breeze Jr.','CHGBR','M');
insert into candidates (name,code,sex) values ('Cyrus S. Cooper II','CYSCO','M');
insert into candidates (name,code,sex) values ('A. Marshall Dennis','AMDEN','M');
insert into candidates (name,code,sex) values ('Samuel Kanyon Doe Jr.','SAKDO','M');
insert into candidates (name,code,sex) values ('George Sluwar Dweh Sr.','GESDW','M');
insert into candidates (name,code,sex) values ('William Y. Glay','WIYGL','M');
insert into candidates (name,code,sex) values ('William K. Glay Sr.','WIKGL','M');
insert into candidates (name,code,sex) values ('Thomas Yaya Nimely','THYNI','M');
insert into candidates (name,code,sex) values ('Zoe Emmanuel Pennue','ZOEPE','M');
insert into candidates (name,code,sex) values ('Cecilia K. Towah','CEKTO','F');
insert into candidates (name,code,sex) values ('Samuel E.S. Badio','SAEBA','M');
insert into candidates (name,code,sex) values ('Amos Yonkon Bartu','AMYBA','M');
insert into candidates (name,code,sex) values ('Albert Tugbe Chie','ALTCH','M');
insert into candidates (name,code,sex) values ('Joseph N. Kpanie II','JONKP','M');
insert into candidates (name,code,sex) values ('Gbenimah Balu Slopadoe I','GBBSL','M');
insert into candidates (name,code,sex) values ('Rosalind Segbe Tonne Sneh','ROSSN','F');
insert into candidates (name,code,sex) values ('Patrice Pokar Weah','PAPWE','M');
insert into candidates (name,code,sex) values ('Gladys G.Y. Beyan','GLGBE','F');
insert into candidates (name,code,sex) values ('Francis Mazuwu Carbah','FRMCA','M');
insert into candidates (name,code,sex) values ('Joseph Kpator Jallah','JOKJA','M');
insert into candidates (name,code,sex) values ('Galakpai Woizee Kortimai','GAWKO','M');
insert into candidates (name,code,sex) values ('Stanley S. Kparkillen','STSKP','M');
insert into candidates (name,code,sex) values ('Alhaji G.V. Kromah','ALGKR','M');
insert into candidates (name,code,sex) values ('Sumo G. Kupee','SUGKU','M');
insert into candidates (name,code,sex) values ('Fomba Varlee Sannoh','FOVSA','M');
insert into candidates (name,code,sex) values ('Stephen J.H. Zargo','STJZA','M');
insert into candidates (name,code,sex) values ('Gabriel Gahie Bedell Jr.','GAGBE','M');
insert into candidates (name,code,sex) values ('Pennoh Wreh Bestman','PEWBE','M');
insert into candidates (name,code,sex) values ('Saah Richard Gbollie','SARGB','M');
insert into candidates (name,code,sex) values ('Clarice Alpha Jah','CLAJA','F');
insert into candidates (name,code,sex) values ('John Fayah Josiah','JOFJO','M');
insert into candidates (name,code,sex) values ('Roland C. Kaine','ROCKA','M');
insert into candidates (name,code,sex) values ('Edna Araminta LLoyd','EDALL','F');
insert into candidates (name,code,sex) values ('J. Stanley Nyumah','JSNYU','M');
insert into candidates (name,code,sex) values ('William Garway Sharpe','WIGSH','M');
insert into candidates (name,code,sex) values ('William R. Slocum','WIRSL','M');
insert into candidates (name,code,sex) values ('Ansu Dao Sonii','ANDSO','M');
insert into candidates (name,code,sex) values ('B. Abraham F. Tengbeh','BAFTE','M');
insert into candidates (name,code,sex) values ('Jim Womba Tornonlah','JIWTO','M');
insert into candidates (name,code,sex) values ('Nathaniel T. Blama Sr.','NATBL','M');
insert into candidates (name,code,sex) values ('Celia Cuffy-Brown','CECUF','F');
insert into candidates (name,code,sex) values ('Miatta Aries Fahnbulleh','MIAFA','F');
insert into candidates (name,code,sex) values ('J. Musu Freeman-Sumo','JMFRE','F');
insert into candidates (name,code,sex) values ('Sheikh Al Moustapha Kouyateh','SHAKO','M');
insert into candidates (name,code,sex) values ('Christopher Zeohn Neyor','CHZNE','M');
insert into candidates (name,code,sex) values ('Benjamin Robert Sanvee','BERSA','M');
insert into candidates (name,code,sex) values ('Robert Alvin Sirleaf','ROASI','M');
insert into candidates (name,code,sex) values ('James Laveli Supuwood','JALSU','M');
insert into candidates (name,code,sex) values ('Ali Sylla','ALSYL','M');
insert into candidates (name,code,sex) values ('George Manneh Weah','GEMWE','M');
insert into candidates (name,code,sex) values ('James N. Anderson II','JANAN','M');
insert into candidates (name,code,sex) values ('John A. Ballout Jr.','JOABA','M');
insert into candidates (name,code,sex) values ('Thomas G. Bedell','THGBE','M');
insert into candidates (name,code,sex) values ('J. Gbleh-bo Brown','JGBRO','M');
insert into candidates (name,code,sex) values ('Bhofal Chambers','BHCHA','M');
insert into candidates (name,code,sex) values ('Abraham Botimo Jackson','ABBJA','M');
insert into candidates (name,code,sex) values ('Roosevelt S. Kla-fleh','ROSKL','M');
insert into candidates (name,code,sex) values ('Isaac Blalu Roland','ISBRO','M');
insert into candidates (name,code,sex) values ('Yamie QuiQui Gbeisay Sr.','YAQGB','M');
insert into candidates (name,code,sex) values ('Edith Lianue Gongloe-Weh','EDLGO','F');
insert into candidates (name,code,sex) values ('Prince Yormie Johnson','PRYJO','M');
insert into candidates (name,code,sex) values ('Joseph D.Z. Korto','JODKO','M');
insert into candidates (name,code,sex) values ('John Leagar Teah','JOLTE','M');
insert into candidates (name,code,sex) values ('Peter Y.B. Weato','PEYWE','M');
insert into candidates (name,code,sex) values ('Jay Jonathan Banney','JAJBA','M');
insert into candidates (name,code,sex) values ('D. Onesimus Banwon','DOBAN','M');
insert into candidates (name,code,sex) values ('J. Josephus Burgess Sr.','JJBUR','M');
insert into candidates (name,code,sex) values ('Jerry Vogar Geedeh','JEVGE','M');
insert into candidates (name,code,sex) values ('Francis Saturday Paye','FRSPA','M');
insert into candidates (name,code,sex) values ('Teplah P. Reeves','TEPRE','F');
insert into candidates (name,code,sex) values ('Rosana Glaypohkpay D.H. Schaack','ROGSC','F');
insert into candidates (name,code,sex) values ('Wellington Geevon Smith','WEGSM','M');
insert into candidates (name,code,sex) values ('Emmanuel S. Toe','EMSTO','M');
insert into candidates (name,code,sex) values ('Minnie Travers Tomah','MITTO','F');
insert into candidates (name,code,sex) values ('Bob Tompoe-Ziankahn','BOTOM','M');
insert into candidates (name,code,sex) values ('Victor Missiongar Wilson','VIMWI','M');
insert into candidates (name,code,sex) values ('Charles Korkor Bardyl','CHKBA','M');
insert into candidates (name,code,sex) values ('Michael A. Cooper','MIACO','M');
insert into candidates (name,code,sex) values ('G. Saygbegee Davis Sr.','GSDAV','M');
insert into candidates (name,code,sex) values ('Daniel G. Johnson','DAGJO','M');
insert into candidates (name,code,sex) values ('Geetor Sarku Saydee','GESSA','M');
insert into candidates (name,code,sex) values ('Andrew Nyenpan Saytue Sr.','ANNSA','M');
insert into candidates (name,code,sex) values ('Jonathan Boycharles Sogbie','JOBSO','M');
insert into candidates (name,code,sex) values ('Conmany B. Wesseh','COBWE','M');
insert into candidates (name,code,sex) values ('Alexander P.B. Yeaher','ALPYE','M');
insert into candidates (name,code,sex) values ('Klahn-Gboloh Jarbah','KLJAR','M');
insert into candidates (name,code,sex) values ('Michael Geegbae Mueller','MIGMU','M');
insert into candidates (name,code,sex) values ('Mobutu Vlah Nyenpan','MOVNY','M');
insert into candidates (name,code,sex) values ('Oscar Jaryee Quiah','OSJQU','M');
insert into candidates (name,code,sex) values ('Juojulue Milton Teahjay','JUMTE','M');
insert into candidates (name,code,sex) values ('Richmond Nagbe Tobii','RINTO','M');
insert into candidates (name,code,sex) values ('Delcontee Juah Wleh Sr.','DEJWL','M');
