-- candidates

insert into candidates (name,code,sex) values ('Nathaniel T. Blama Sr.','NATBL','M');
insert into candidates (name,code,sex) values ('Celia Cuffy-Brown','CECUF','F');
insert into candidates (name,code,sex) values ('Miatta Aries Fahnbulleh','MIAFA','F');
insert into candidates (name,code,sex) values ('J. Musu Freeman-Sumo','JMFRE','F');
insert into candidates (name,code,sex) values ('Sheikh Al Moustapha Kouyateh','SHAKO','M');
insert into candidates (name,code,sex) values ('Christopher Zeohn Neyor','CHZNE','M');
insert into candidates (name,code,sex) values ('Benjamin Robert Sanvee','BERSA','M');
insert into candidates (name,code,sex) values ('Robert Alvin Sirleaf','ROASI','M');
insert into candidates (name,code,sex) values ('James Laveli Supuwood','JALSU','M');
insert into candidates (name,code,sex) values ('Ali Sylla','ALSYL','M');
insert into candidates (name,code,sex) values ('George Manneh Weah','GEMWE','M');


-- parties

insert into parties (name,code) values ('All Liberia Coalition Party', 'ALCOP');
insert into parties (name,code) values ('Alliance for Peace and Democracy', 'APD');
insert into parties (name,code) values ('Congress for Democratic Change', 'CDC');
insert into parties (name,code) values ('Citizens Unification Party', 'CUP');
insert into parties (name,code) values ('Free Democratic Party', 'FDP');
insert into parties (name,code) values ('Freedom Alliance Party of Liberia', 'FAPL');
insert into parties (name,code) values ('Grassroot Democratic Party of Liberia', 'GDPL');
insert into parties (name,code) values ('Labor Party of Liberia', 'LPL');
insert into parties (name,code) values ('Liberia Destiny Party', 'LDP');
insert into parties (name,code) values ('Liberia Empowerment Party', 'LEP');
insert into parties (name,code) values ('Liberia Equal Rights Party', 'LERP');
insert into parties (name,code) values ('Liberia National Union', 'LNU');
insert into parties (name,code) values ('Liberty Party', 'LP');
insert into parties (name,code) values ('Liberia Reconstruction Party', 'LRP');
insert into parties (name,code) values ('Liberia Transformation Party', 'LTP');
insert into parties (name,code) values ('Movement for Progressive Change', 'MPC');
insert into parties (name,code) values ('Majority Party of Liberia', 'MPL');
insert into parties (name,code) values ('National Democratic Coalition', 'NDC');
insert into parties (name,code) values ('National Democratic Party of Liberia', 'NDPL');
insert into parties (name,code) values ('National Party of Liberia', 'NPL');
insert into parties (name,code) values ('National Reformation Party', 'NRP');
insert into parties (name,code) values ('National Social Democratic Party of Liberia', 'NSDPL');
insert into parties (name,code) values ('National Union for Democratic Progress', 'NUDP');
insert into parties (name,code) values ('National Vision Party of Liberia', 'NVPL');
insert into parties (name,code) values ('New Deal Movement', 'NDM');
insert into parties (name,code) values ('Original Congress Party of Liberia', 'OCPOL');
insert into parties (name,code) values ('Progressive Democratic Party', 'PDP');
insert into parties (name,code) values ('Progressive People''s Party', 'PPP');
insert into parties (name,code) values ('Reformed United Liberia Party', 'RULP');
insert into parties (name,code) values ('Republican Party', 'RP');
insert into parties (name,code) values ('Union of Liberian Democrats', 'ULD');
insert into parties (name,code) values ('Unity Party', 'UP');
insert into parties (name,code) values ('Victory for Change Party', 'VCP');
insert into parties (name,code) values ('Independent Candidate', 'IND');
insert into parties (name,code) values ('Alternative National Congress', 'ANC');
insert into parties (name,code) values ('National Patriotic Party', 'NPP');
insert into parties (name,code) values ('Liberian National Union', 'LINU');
insert into parties (name,code) values ('People''s Unification Party', 'PUP');

update parties set color = 'FB4226' where code = 'FAPL';
update parties set color = 'C720D0' where code = 'LEP';
update parties set color = 'FBDE26' where code = 'MPC';
update parties set color = '2046D0' where code = 'NUDP';
update parties set color = 'FF4388' where code = 'ULD';
update parties set color = 'F28E1E' where code = 'LP';
update parties set color = '29A6DD' where code = 'CDC';
update parties set color = 'BD282E' where code = 'NRP';
update parties set color = 'EB5A23' where code = 'NPL';
update parties set color = '2D318C' where code = 'ALCOP';
update parties set color = '2D318C' where code = 'LTP';
update parties set color = '008D45' where code = 'UP';


-- counties

insert into counties (name, capital, long_code, short_code, latitude, longitude) values ('Montserrado', 'Bensonville', 'MONT', 'MT', 6.5, -10.5);


-- districts

insert into districts (number,county_id) values ('1', lookup_county_id('MONT'));
insert into districts (number,county_id) values ('2', lookup_county_id('MONT'));
insert into districts (number,county_id) values ('3', lookup_county_id('MONT'));
insert into districts (number,county_id) values ('4', lookup_county_id('MONT'));
insert into districts (number,county_id) values ('5', lookup_county_id('MONT'));
insert into districts (number,county_id) values ('6', lookup_county_id('MONT'));
insert into districts (number,county_id) values ('7', lookup_county_id('MONT'));
insert into districts (number,county_id) values ('8', lookup_county_id('MONT'));
insert into districts (number,county_id) values ('9', lookup_county_id('MONT'));
insert into districts (number,county_id) values ('10', lookup_county_id('MONT'));
insert into districts (number,county_id) values ('11', lookup_county_id('MONT'));
insert into districts (number,county_id) values ('12', lookup_county_id('MONT'));
insert into districts (number,county_id) values ('13', lookup_county_id('MONT'));
insert into districts (number,county_id) values ('14', lookup_county_id('MONT'));
insert into districts (number,county_id) values ('15', lookup_county_id('MONT'));
insert into districts (number,county_id) values ('16', lookup_county_id('MONT'));
insert into districts (number,county_id) values ('17', lookup_county_id('MONT'));


-- precincts

insert into precincts (code,name,district_id,county_id) values ('30002','Goba Town Public School ',lookup_district_id('MONT', '1'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30003','Sackie Town Public School ',lookup_district_id('MONT', '1'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30028','Careysburg High School ',lookup_district_id('MONT', '1'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30029','Careysburg Admin Building ',lookup_district_id('MONT', '1'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30072','Crozierville Town Hall ',lookup_district_id('MONT', '1'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30101','Euphemial Barclay School ',lookup_district_id('MONT', '1'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30102','Morris Farm School ',lookup_district_id('MONT', '1'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30103','Blopa Public School ',lookup_district_id('MONT', '1'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30104','Fendall Public School ',lookup_district_id('MONT', '1'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30105','Fendall U.L. Palava Hut ',lookup_district_id('MONT', '1'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30138','Children Home School ',lookup_district_id('MONT', '1'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30140','Youth Camp Auditorium ',lookup_district_id('MONT', '1'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30141','Freeman Reserved Public Sch',lookup_district_id('MONT', '1'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30147','Bernand Curve Palava Hut ',lookup_district_id('MONT', '1'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30148','David A. Day Mem. Lutheran Sch. ',lookup_district_id('MONT', '1'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30149','Raymond Camp School ',lookup_district_id('MONT', '1'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30170','Kartoe Public School ',lookup_district_id('MONT', '1'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30177','Kingsville Public School ',lookup_district_id('MONT', '1'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30178','Kingsville Public School ',lookup_district_id('MONT', '1'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30179','15th Gate Community School ',lookup_district_id('MONT', '1'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30180','Kpayaquelleh Palava Hut ',lookup_district_id('MONT', '1'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30189','Louisiana Waterside Comm. Sch. ',lookup_district_id('MONT', '1'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30190','King''s Farm Community School ',lookup_district_id('MONT', '1'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30191','Mary Paye Farm Public School ',lookup_district_id('MONT', '1'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30194','Gwee Town Palava Hut ',lookup_district_id('MONT', '1'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30195','Tarquoi Town Palava Hut ',lookup_district_id('MONT', '1'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30196','Koon Town Public School ',lookup_district_id('MONT', '1'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30197','Manamu Town Palava Hut ',lookup_district_id('MONT', '1'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30215','Zingbor Town Hall ',lookup_district_id('MONT', '1'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30270','Sasstown Community School ',lookup_district_id('MONT', '1'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30328','New Land IDP Camp Comm. Hall ',lookup_district_id('MONT', '1'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30329','New Land IDP Camp Comm. Hall ',lookup_district_id('MONT', '1'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30330','Clean Town Palava Hut ',lookup_district_id('MONT', '1'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30331','Zannah Town Public School ',lookup_district_id('MONT', '1'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30332','Moisee Town Public School ',lookup_district_id('MONT', '1'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30333','Yeakpai Town Public School ',lookup_district_id('MONT', '1'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30334','Yeagbah Town Public School ',lookup_district_id('MONT', '1'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30335','Nyehn Town Public School ',lookup_district_id('MONT', '1'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30432','C. H. Henry Public School ',lookup_district_id('MONT', '1'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30433','Jesus Christ Children Int''l School ',lookup_district_id('MONT', '1'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30434','Hart Town Hall ',lookup_district_id('MONT', '1'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30435','Yarkpazuah Palava Hut ',lookup_district_id('MONT', '1'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30436','Pleemu Public School ',lookup_district_id('MONT', '1'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30036','Johnsonville Public School ',lookup_district_id('MONT', '2'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30091','Fairfield Baptist School ',lookup_district_id('MONT', '2'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30099','Hope For Life School ',lookup_district_id('MONT', '2'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30100','Our Lady of Fatama School ',lookup_district_id('MONT', '2'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30192','Light Enterprises Academy &  Vocational School System',lookup_district_id('MONT', '2'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30193','YMCA - Nekely Town ',lookup_district_id('MONT', '2'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30213','NRC School ',lookup_district_id('MONT', '2'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30214','Child Friendly Space ',lookup_district_id('MONT', '2'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30223','Monrovia Vocational Training Cen. ',lookup_district_id('MONT', '2'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30224','Monrovia Vocational Training Cen. ',lookup_district_id('MONT', '2'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30225','New Hope Academy ',lookup_district_id('MONT', '2'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30226','Bassa Town Community School ',lookup_district_id('MONT', '2'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30227','St. Francis School ',lookup_district_id('MONT', '2'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30228','Calvary Temple A.G.M. High Sch',lookup_district_id('MONT', '2'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30229','Calvary Temple A.G.M. High Sch. ',lookup_district_id('MONT', '2'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30230','Ma Bendu I. Sheriff School ',lookup_district_id('MONT', '2'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30231','Muslim Solidarity Arabic & English Sch.',lookup_district_id('MONT', '2'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30232','Star Baptist School ',lookup_district_id('MONT', '2'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30092','Aaron G. Burgess Momerial Aca. ',lookup_district_id('MONT', '3'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30093','Christian Methodist School ',lookup_district_id('MONT', '3'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30094','New Jerusalem Baptist Church ',lookup_district_id('MONT', '3'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30095','Salvation Army ',lookup_district_id('MONT', '3'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30096','Int''l Christian Sch. of Prime Sys. ',lookup_district_id('MONT', '3'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30097','Small Catholic & IDP Camp ',lookup_district_id('MONT', '3'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30271','Revival Temple A.G.M School ',lookup_district_id('MONT', '3'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30272','Jawalla Community School ',lookup_district_id('MONT', '3'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30273','Billie Call Christian Institute ',lookup_district_id('MONT', '3'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30274','Billie Call Christian Institute ',lookup_district_id('MONT', '3'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30275','Victorial A. William High Sch. ',lookup_district_id('MONT', '3'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30276','Factory Comm. Christian Aca. ',lookup_district_id('MONT', '3'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30277','Practical Trade Training Cen. ',lookup_district_id('MONT', '3'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30280','Messiah Mission School ',lookup_district_id('MONT', '3'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30283','David G. Barshell Sr. School ',lookup_district_id('MONT', '3'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30288','Paynesville Central Aca. ',lookup_district_id('MONT', '3'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30108','Christian Home Ministries Church Int''l',lookup_district_id('MONT', '4'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30109','Omega Comm. Christian Aca. ',lookup_district_id('MONT', '4'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30110','30110 Brighter Day Perparatory School',lookup_district_id('MONT', '4'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30111','Soul Clinic Mission/Maggie Lampkins Institute',lookup_district_id('MONT', '4'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30112','Soul Clinic Mission/Maggie Lampkins Institute',lookup_district_id('MONT', '4'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30113','Kingdom Foundation Institute ',lookup_district_id('MONT', '4'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30114','St. Samuel Elem .& Jr. High Sch.',lookup_district_id('MONT', '4'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30115','S. Patrick Jallah School ',lookup_district_id('MONT', '4'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30116','Tomorrow People Foundation ',lookup_district_id('MONT', '4'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30117','Sammy M. Dukuly School ',lookup_district_id('MONT', '4'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30119','Seymour Grann School ',lookup_district_id('MONT', '4'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30120','Seymour Grann School ',lookup_district_id('MONT', '4'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30122','Rik-C Day Care, Nursery & Pre- Sch. ',lookup_district_id('MONT', '4'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30123','Dave R. Inman Int''l School ',lookup_district_id('MONT', '4'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30124','Zinah Foundation School ',lookup_district_id('MONT', '4'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30125','Stronger Hope Central Academy',lookup_district_id('MONT', '4'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30126','Rev. Mother Sarah Sch. System ',lookup_district_id('MONT', '4'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30127','William Bean Institute/Worldwide',lookup_district_id('MONT', '4'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30128','Nathan E. Gibson School ',lookup_district_id('MONT', '4'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30129','Nathan E. Gibson School ',lookup_district_id('MONT', '4'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30278','Whein Town Public School ',lookup_district_id('MONT', '4'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30279','Charles F. Caine School ',lookup_district_id('MONT', '4'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30098','Credit Union Building ',lookup_district_id('MONT', '5'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30121','Paynesville Community School ',lookup_district_id('MONT', '5'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30243','Dyfater School ',lookup_district_id('MONT', '5'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30244','Paynesville Town Hall ',lookup_district_id('MONT', '5'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30245','Christ Miracle of Faith Sch. Sys. ',lookup_district_id('MONT', '5'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30246','Bonner Memorial Christian Aca. ',lookup_district_id('MONT', '5'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30247','Sir Kerry St. Johnston School ',lookup_district_id('MONT', '5'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30248','Repentence Baptist School ',lookup_district_id('MONT', '5'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30284','St. Mathew Lutheran School ',lookup_district_id('MONT', '5'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30285','Victory Chapel School ',lookup_district_id('MONT', '5'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30286','Gayee Trade International Sch. ',lookup_district_id('MONT', '5'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30287','Kalita School ',lookup_district_id('MONT', '5'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30289','Seat of Wisdom School System ',lookup_district_id('MONT', '5'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30290','Rock International School ',lookup_district_id('MONT', '5'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30303','James Kin Freeman Mem.l Sch. ',lookup_district_id('MONT', '5'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30307','Kendejah High School/Rehab ',lookup_district_id('MONT', '6'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30308','Kendejah Community School ',lookup_district_id('MONT', '6'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30309','Love A Child Orphanage Home ',lookup_district_id('MONT', '6'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30310','Helen Teah Memorial Christian Inst.',lookup_district_id('MONT', '6'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30311','Cavalry Chapel Mission Sch. ',lookup_district_id('MONT', '6'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30312','Solid Rock Christian School ',lookup_district_id('MONT', '6'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30313','Sis. Kathleen McQuire Memo. Catholic High School',lookup_district_id('MONT', '6'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30319','Broluco Christian School Sys. ',lookup_district_id('MONT', '6'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30320','30320 David Gueh Memorial UMC ',lookup_district_id('MONT', '6'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30321','30321 Mount Carmel Institute ',lookup_district_id('MONT', '6'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30322','Wilbel Foundation Elem. Sch. ',lookup_district_id('MONT', '6'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30323','Carver Mission School ',lookup_district_id('MONT', '6'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30324','Seventh Day Adventist Sch. ',lookup_district_id('MONT', '6'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30325','Immanuel Christian Aca. ',lookup_district_id('MONT', '6'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30047','M.V. Massaquoi ',lookup_district_id('MONT', '7'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30048','M.V. Massaquoi ',lookup_district_id('MONT', '7'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30049','Our Lady Star of the Sea ',lookup_district_id('MONT', '7'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30050','Our Lady Star of the Sea ',lookup_district_id('MONT', '7'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30106','West Point Market ',lookup_district_id('MONT', '7'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30107','John Kofi Asmeh UMC ',lookup_district_id('MONT', '7'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30142','West Point Admin. Building ',lookup_district_id('MONT', '7'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30143','West Point Admin. Building ',lookup_district_id('MONT', '7'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30257','West Point Catholic School ',lookup_district_id('MONT', '7'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30258','West Point Catholic School ',lookup_district_id('MONT', '7'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30262','LEC Head Office ',lookup_district_id('MONT', '7'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30263','LEC Head Office ',lookup_district_id('MONT', '7'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30368','Newport High School ',lookup_district_id('MONT', '7'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30369','Newport High School ',lookup_district_id('MONT', '7'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30370','Family Nursing Center ',lookup_district_id('MONT', '7'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30371','Cathedral Catholic School ',lookup_district_id('MONT', '7'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30372','Cathedral Catholic School ',lookup_district_id('MONT', '7'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30373','Good Samaritan School ',lookup_district_id('MONT', '7'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30374','Godwin Prepartory School ',lookup_district_id('MONT', '7'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30375','National Housing Bank ',lookup_district_id('MONT', '7'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30421','A.G.M. High School ',lookup_district_id('MONT', '7'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30422','A.G.M. High School ',lookup_district_id('MONT', '7'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30423','Sports Commission ',lookup_district_id('MONT', '7'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30424','St. Samuel High School ',lookup_district_id('MONT', '7'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30427','J.L. Gibson School ',lookup_district_id('MONT', '7'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30428','J.L. Gibson School ',lookup_district_id('MONT', '7'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30429','St. Theresa Convent ',lookup_district_id('MONT', '7'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30430','St. Theresa Convent ',lookup_district_id('MONT', '7'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30431','J.J. Ross High School ',lookup_district_id('MONT', '7'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30347','William V.S. Tubman High Sch. ',lookup_district_id('MONT', '8'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30348','William V.S. Tubman High Sch. ',lookup_district_id('MONT', '8'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30350','William C. Jones School ',lookup_district_id('MONT', '8'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30351','Nancy B. Doe Jorkpen Town Market',lookup_district_id('MONT', '8'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30352','Christ & Selina Hook Mem. Sch. ',lookup_district_id('MONT', '8'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30353','Vision Academy ',lookup_district_id('MONT', '8'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30354','ACFI Building ',lookup_district_id('MONT', '8'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30355','Monrovia Free Pentecostal Sch',lookup_district_id('MONT', '8'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30359','Lorma Quarter Elem. School ',lookup_district_id('MONT', '8'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30360','Lorma Quarter Elem. School ',lookup_district_id('MONT', '8'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30361','Bassa Community High Sch. ',lookup_district_id('MONT', '8'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30362','New Jeruselam School ',lookup_district_id('MONT', '8'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30363','LU Monrovia Campus ',lookup_district_id('MONT', '8'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30364','LU Monrovia Campus ',lookup_district_id('MONT', '8'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30407','Monrovia Dem. Elem. Sch. ',lookup_district_id('MONT', '8'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30408','Monrovia Dem. Elem. Sch. ',lookup_district_id('MONT', '8'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30409','G.W. Gibson High School ',lookup_district_id('MONT', '8'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30410','G.W. Gibson High School ',lookup_district_id('MONT', '8'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30411','Y.M.C.A Building ',lookup_district_id('MONT', '8'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30412','Y.M.C.A Building ',lookup_district_id('MONT', '8'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30413','Slipway Elementary School ',lookup_district_id('MONT', '8'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30414','Brighter Star Int''l School ',lookup_district_id('MONT', '8'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30415','C.D. King Elem. School ',lookup_district_id('MONT', '8'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30416','C.D. King Elem. School ',lookup_district_id('MONT', '8'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30417','Soniwein Comm. Public Sch. ',lookup_district_id('MONT', '8'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30425','Rally Time Market ',lookup_district_id('MONT', '8'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30426','Rally Time Market ',lookup_district_id('MONT', '8'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30240','Apostlic Building Foundation School',lookup_district_id('MONT', '9'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30349','A. Gienn Jr. High School ',lookup_district_id('MONT', '9'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30378','Lutheran International School System',lookup_district_id('MONT', '9'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30379','H.B. William Royal School ',lookup_district_id('MONT', '9'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30380','Barnes Foundation School ',lookup_district_id('MONT', '9'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30381','Barnes Foundation School ',lookup_district_id('MONT', '9'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30382','Building for Tomorrow Sch. ',lookup_district_id('MONT', '9'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30383','Building for Tomorrow Sch. ',lookup_district_id('MONT', '9'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30384','Nancy B. Doe Public Sch. ',lookup_district_id('MONT', '9'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30385','Nancy B. Doe Public Sch. ',lookup_district_id('MONT', '9'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30386','SOS Children Village ',lookup_district_id('MONT', '9'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30387','SOS Children Village ',lookup_district_id('MONT', '9'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30388','Emmanuel Temper Sch. ',lookup_district_id('MONT', '9'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30389','Bright Stone Academy ',lookup_district_id('MONT', '9'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30390','Wroto Town God of Mercy Sch.',lookup_district_id('MONT', '9'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30392','Fiama Community School ',lookup_district_id('MONT', '9'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30393','Fiama Community School ',lookup_district_id('MONT', '9'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30394','Fiama Calvary Baptist Sch. ',lookup_district_id('MONT', '9'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30395','Fiama Calvary Baptist Sch. ',lookup_district_id('MONT', '9'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30396','Philip Perparatory School ',lookup_district_id('MONT', '9'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30397','Philip Perparatory School ',lookup_district_id('MONT', '9'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30398','St. Peter Lutheran School ',lookup_district_id('MONT', '9'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30399','St. Peter Lutheran School ',lookup_district_id('MONT', '9'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30400','Smythe institue ',lookup_district_id('MONT', '9'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30401','Calvary Baptish School ',lookup_district_id('MONT', '9'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30402','ACFI Lacy Kofi Memorial Academy',lookup_district_id('MONT', '9'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30403','St. Mark School',lookup_district_id('MONT', '9'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30404','New Matadi Comm. School ',lookup_district_id('MONT', '9'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30405','Child Foundation Academy ',lookup_district_id('MONT', '9'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30406','Don Bosco Youth Center ',lookup_district_id('MONT', '9'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30004','Steve-Ernest Memorial Christian Academy',lookup_district_id('MONT', '10'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30024','Faith Foundation ',lookup_district_id('MONT', '10'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30025','JHP Hope Academy ',lookup_district_id('MONT', '10'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30060','Greater Works Academy ',lookup_district_id('MONT', '10'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30061','Better Future Christian Inst. ',lookup_district_id('MONT', '10'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30062','R.C. Lawson Institute ',lookup_district_id('MONT', '10'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30063','Joe B. Tate School ',lookup_district_id('MONT', '10'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30064','Susan Berry School ',lookup_district_id('MONT', '10'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30065','Wells-Hairston School ',lookup_district_id('MONT', '10'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30066','Open Bible school ',lookup_district_id('MONT', '10'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30067','Open Bible school ',lookup_district_id('MONT', '10'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30077','A.G.M. School Building ',lookup_district_id('MONT', '10'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30078','Namuwa English & Arabic School',lookup_district_id('MONT', '10'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30133','Gaye Town Public School ',lookup_district_id('MONT', '10'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30134','St. Andrew Lutheran School ',lookup_district_id('MONT', '10'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30173','Bethlehem Baptist School ',lookup_district_id('MONT', '10'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30174','People Institute Building ',lookup_district_id('MONT', '10'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30233','Nippay Town Public School ',lookup_district_id('MONT', '10'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30241','Fofana Islamic School ',lookup_district_id('MONT', '10'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30242','Mason Center School ',lookup_district_id('MONT', '10'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30251','Peace Island Comm. Sch. ',lookup_district_id('MONT', '10'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30252','Deolakeh Memorial Elem. & Jr. High Sch.',lookup_district_id('MONT', '10'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30291','Ford Madden Christian Aca. ',lookup_district_id('MONT', '10'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30292','Guildford George Tompkins Jr.& Sr. High school',lookup_district_id('MONT', '10'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30304','Rebecca J. Wilson School ',lookup_district_id('MONT', '10'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30305','Bethel Temple African Glory Pentecostal Church',lookup_district_id('MONT', '10'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30306','Amalca Cabral Estate Pal. Hut',lookup_district_id('MONT', '10'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30006','E. Jonathan Goodridge Sch. ',lookup_district_id('MONT', '11'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30007','E. Jonathan Goodridge Sch. ',lookup_district_id('MONT', '11'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30008','Gardnersville Town Hall ',lookup_district_id('MONT', '11'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30009','Step of Faith Academy ',lookup_district_id('MONT', '11'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30013','Bardnersville Comm. Inst. ',lookup_district_id('MONT', '11'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30014','Shirley Kolmer Catholic Sch. ',lookup_district_id('MONT', '11'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30023','Caldwell Market ',lookup_district_id('MONT', '11'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30073','Bardnesville Public School ',lookup_district_id('MONT', '11'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30074',' (J & M) Jerbo & Martha Sch. ',lookup_district_id('MONT', '11'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30079','Dixville Public School ',lookup_district_id('MONT', '11'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30090','Grace Baptist Church Sch. ',lookup_district_id('MONT', '11'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30144','Lombardia Int''l School Sys. ',lookup_district_id('MONT', '11'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30154','Duja School ',lookup_district_id('MONT', '11'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30155','Jimmy Jolocon School ',lookup_district_id('MONT', '11'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30158','Seku Ibrahim Sheriff Elem. & Jr. High School',lookup_district_id('MONT', '11'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30168','Bardnersville Town Hall ',lookup_district_id('MONT', '11'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30169','New Life Christian Academy ',lookup_district_id('MONT', '11'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30269','Samukal Community Center ',lookup_district_id('MONT', '11'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30326','E.T.M.I School ',lookup_district_id('MONT', '11'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30010','West African Christian Inst. ',lookup_district_id('MONT', '12'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30051','Wells-Hairston School ',lookup_district_id('MONT', '12'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30052','Wells-Hairston School ',lookup_district_id('MONT', '12'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30053','A.G.M. School ',lookup_district_id('MONT', '12'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30054','Christain David School ',lookup_district_id('MONT', '12'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30055','Free Penticostal Global Mission Church',lookup_district_id('MONT', '12'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30157','St. Philip School ',lookup_district_id('MONT', '12'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30159','James Tue High School ',lookup_district_id('MONT', '12'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30164','Emmanuel Comm. Polytechnic Jr. & Sr. School',lookup_district_id('MONT', '12'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30165','Emmanuel Comm. Polytechnic Jr. & Sr. School',lookup_district_id('MONT', '12'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30166','Euphemia Abdullia Sch. ',lookup_district_id('MONT', '12'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30167','Euphemia Abdullia Sch. ',lookup_district_id('MONT', '12'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30171','Star International Academy ',lookup_district_id('MONT', '12'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30172','Wisdom Home Heritage Sch. ',lookup_district_id('MONT', '12'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30216','St. Magarette School System ',lookup_district_id('MONT', '12'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30217','Liberia Christian Comm. Col. ',lookup_district_id('MONT', '12'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30264','OPHANAGE/WACI ',lookup_district_id('MONT', '12'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30265','Maranatha A.G.M School ',lookup_district_id('MONT', '12'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30281','Picoli Preparatory School ',lookup_district_id('MONT', '12'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30282','Richand Hunter School ',lookup_district_id('MONT', '12'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30294','Special Project School ',lookup_district_id('MONT', '12'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30295','Wesleyan School ',lookup_district_id('MONT', '12'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30012','Mother Kebbeh''s Academy ',lookup_district_id('MONT', '13'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30056','Allen Bryant School ',lookup_district_id('MONT', '13'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30057','Allen Bryant School ',lookup_district_id('MONT', '13'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30058','Deaf Ministry INC/ Elizabeth Silem School of Hope',lookup_district_id('MONT', '13'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30059','Elizabeth Blunt School ',lookup_district_id('MONT', '13'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30118','Flahn Town Comm. School ',lookup_district_id('MONT', '13'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30130','R & R Central ',lookup_district_id('MONT', '13'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30131','R & R Central ',lookup_district_id('MONT', '13'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30146','Kula Memorial Academy ',lookup_district_id('MONT', '13'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30152','Freeway Baptish School ',lookup_district_id('MONT', '13'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30153','Freeway Baptish School ',lookup_district_id('MONT', '13'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30156','St. Michael Elem. Sch. ',lookup_district_id('MONT', '13'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30161','Trumpet of Faith School ',lookup_district_id('MONT', '13'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30209','St. James Episcopal Church ',lookup_district_id('MONT', '13'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30218','St. Michael High Sch. ',lookup_district_id('MONT', '13'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30219','St. Michael High Sch. ',lookup_district_id('MONT', '13'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30220','Christiana Comfort Bedell Preparatory School',lookup_district_id('MONT', '13'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30221','William Gabriel Kpolleh Memorial High School',lookup_district_id('MONT', '13'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30222','Jennie Prepartory School ',lookup_district_id('MONT', '13'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30237','Kula Memorial Academy ',lookup_district_id('MONT', '13'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30238','Grace A.G.M. School ',lookup_district_id('MONT', '13'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30239','Grace A.G.M. School ',lookup_district_id('MONT', '13'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30293','Freeway Baptist School ',lookup_district_id('MONT', '13'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30296','New Life School ',lookup_district_id('MONT', '13'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30314','Salvation & Deliverance Christ Academy',lookup_district_id('MONT', '13'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30315','Henri Dennis Methodist Sch. ',lookup_district_id('MONT', '13'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30030','Central Clara Town Hut ',lookup_district_id('MONT', '14'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30031','Central Clara Town Hut ',lookup_district_id('MONT', '14'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30032','Fanina Isaac School ',lookup_district_id('MONT', '14'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30033','Clara Town Central Sch. ',lookup_district_id('MONT', '14'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30034','Clara Town Central Sch. ',lookup_district_id('MONT', '14'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30035','James Doe Young School ',lookup_district_id('MONT', '14'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30068','Mac Foundation School ',lookup_district_id('MONT', '14'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30069','Mac Foundation School ',lookup_district_id('MONT', '14'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30139','Savaco Community School ',lookup_district_id('MONT', '14'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30150','Royal Foundation School ',lookup_district_id('MONT', '14'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30151','Royal Foundation School ',lookup_district_id('MONT', '14'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30249','Paity Town Gas Station ',lookup_district_id('MONT', '14'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30250','Paity Town Gas Station ',lookup_district_id('MONT', '14'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30253','Ophelia Hoff Saytuman Sch. ',lookup_district_id('MONT', '14'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30254','Timosa Elementary School ',lookup_district_id('MONT', '14'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30266','Marvia Sonu Elem. School ',lookup_district_id('MONT', '14'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30267','Marvia Sonu Elem. School ',lookup_district_id('MONT', '14'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30268','Marvia Sonu Elem. School ',lookup_district_id('MONT', '14'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30297','Maude Popla Mem. Sch. ',lookup_district_id('MONT', '14'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30298','S.K.D. Comm. Elem. School',lookup_district_id('MONT', '14'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30299','S.K.D. Comm. Elem. School ',lookup_district_id('MONT', '14'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30300','Busroad Memorial Institute ',lookup_district_id('MONT', '14'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30301','Busroad Memorial Institute ',lookup_district_id('MONT', '14'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30337','Vai Town Market Block Fac. ',lookup_district_id('MONT', '14'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30338','Imam Adullah Tunis Sch. ',lookup_district_id('MONT', '14'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30339','Imam Adullah Tunis Sch. ',lookup_district_id('MONT', '14'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30015','Blamo Town Palava Hut ',lookup_district_id('MONT', '15'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30016','Bong Mines Bridge Luth. Sch. ',lookup_district_id('MONT', '15'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30017','Bong Mines Bridge Luth. Sch. ',lookup_district_id('MONT', '15'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30018','King Peter Town School ',lookup_district_id('MONT', '15'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30019','King Peter Town School ',lookup_district_id('MONT', '15'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30020','Caldwell New Georgia Pub. Sch. ',lookup_district_id('MONT', '15'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30021','Sims Community School ',lookup_district_id('MONT', '15'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30027','Marantha Baptist School ',lookup_district_id('MONT', '15'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30037','St. Matthew UMC School ',lookup_district_id('MONT', '15'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30038','St. Matthew UMC School ',lookup_district_id('MONT', '15'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30039','Life Terbanacle Int''l. School ',lookup_district_id('MONT', '15'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30040','Central Logan Town Market ',lookup_district_id('MONT', '15'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30041','Central Logan Town Market ',lookup_district_id('MONT', '15'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30132','Logan Town New Testament Academy',lookup_district_id('MONT', '15'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30135','Samuel T. Kun School ',lookup_district_id('MONT', '15'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30136','Samuel T. Kun School ',lookup_district_id('MONT', '15'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30160','Isaac G. McCauley School ',lookup_district_id('MONT', '15'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30162','Boatswain Jr. High School ',lookup_district_id('MONT', '15'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30163','Boatswain Jr. High School ',lookup_district_id('MONT', '15'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30175','Kabedu Bessi School ',lookup_district_id('MONT', '15'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30176','Kabedu Bessi School ',lookup_district_id('MONT', '15'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30186','Donald N. K. Karanas ',lookup_district_id('MONT', '15'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30187','Wesleyan Church ',lookup_district_id('MONT', '15'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30188','Myrae E. Simpson Comm. Sch. ',lookup_district_id('MONT', '15'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30327','Angeline W. Allison School ',lookup_district_id('MONT', '15'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30437','Joanna Antor Elem. School ',lookup_district_id('MONT', '15'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30438','Joanna Antor Elem. School ',lookup_district_id('MONT', '15'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30439','St. Edward Catholic School ',lookup_district_id('MONT', '15'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30440','St. Edward Catholic School ',lookup_district_id('MONT', '15'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30441','St. Edward Catholic School ',lookup_district_id('MONT', '15'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30022','Wesleyan Academy ',lookup_district_id('MONT', '16'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30042','New Kru Town Adm. Building ',lookup_district_id('MONT', '16'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30043','Tomorrow Children Int''l ',lookup_district_id('MONT', '16'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30044','Tomorrow Children Int''l ',lookup_district_id('MONT', '16'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30045','Greater Vision School ',lookup_district_id('MONT', '16'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30070','Mark Richard Jr. High School ',lookup_district_id('MONT', '16'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30071','Mark Richard Jr. High School ',lookup_district_id('MONT', '16'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30080','Samuel Slewon Doe Institute ',lookup_district_id('MONT', '16'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30081','Victor Molu Institute ',lookup_district_id('MONT', '16'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30082','St. Mary High School ',lookup_district_id('MONT', '16'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30083','St. Mary High School ',lookup_district_id('MONT', '16'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30084','Diana E.Davis High School ',lookup_district_id('MONT', '16'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30085','Diana E.Davis High School ',lookup_district_id('MONT', '16'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30086','A.G.M. School ',lookup_district_id('MONT', '16'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30087','A.G.M. School ',lookup_district_id('MONT', '16'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30088','God is Our Light School ',lookup_district_id('MONT', '16'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30089','God is Our Light School ',lookup_district_id('MONT', '16'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30181','St. Thomas Elem. School ',lookup_district_id('MONT', '16'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30182','New kru Town AG School ',lookup_district_id('MONT', '16'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30183','Momboe Town Comm. Sch. ',lookup_district_id('MONT', '16'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30184','New Kru Town Jr. High Sch. ',lookup_district_id('MONT', '16'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30185','New Kru Town Jr. High Sch. ',lookup_district_id('MONT', '16'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30211','NKT Elem. & Jr. High Sch. ',lookup_district_id('MONT', '16'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30212','NKT Elem. & Jr. High Sch. ',lookup_district_id('MONT', '16'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30234','D. Tweh High School ',lookup_district_id('MONT', '16'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30235','D. Tweh High School ',lookup_district_id('MONT', '16'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30236','D. Tweh High School ',lookup_district_id('MONT', '16'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30255','New Era School ',lookup_district_id('MONT', '16'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30256','New Era School ',lookup_district_id('MONT', '16'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30259','Bishop Nah Dixon School ',lookup_district_id('MONT', '16'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30260','Bishop Nah Dixon School ',lookup_district_id('MONT', '16'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30261','Barclay Nyenfueh School ',lookup_district_id('MONT', '16'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30316','St. Paul Bridge Elem. School ',lookup_district_id('MONT', '16'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30317','St. Paul Bridge Elem. School ',lookup_district_id('MONT', '16'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30318','Rev. Johnson W. T. Foundation Sch.',lookup_district_id('MONT', '16'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30340','Triump of God Int''l School ',lookup_district_id('MONT', '16'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30005','Komah Public School ',lookup_district_id('MONT', '17'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30011','W.D. Coleman High Sch. ',lookup_district_id('MONT', '17'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30026','Central Arthington Pa. Hut ',lookup_district_id('MONT', '17'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30046','Royesville Public School ',lookup_district_id('MONT', '17'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30075','Neekon Public School ',lookup_district_id('MONT', '17'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30076','Samie Public School ',lookup_district_id('MONT', '17'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30137','Jallabah Public school ',lookup_district_id('MONT', '17'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30198','Sarah Barclay Public Sch. ',lookup_district_id('MONT', '17'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30199','Virginia Christian Aca. ',lookup_district_id('MONT', '17'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30200','Banjor Public School Cen. ',lookup_district_id('MONT', '17'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30201','Virginia Public School ',lookup_district_id('MONT', '17'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30202','Banjor United Comm. Cen',lookup_district_id('MONT', '17'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30203','Pamela Kay School ',lookup_district_id('MONT', '17'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30204','Mango Town Clinic ',lookup_district_id('MONT', '17'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30205','Gbarteah Palava Hut ',lookup_district_id('MONT', '17'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30206','Goyee Jr. High School ',lookup_district_id('MONT', '17'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30207','FAWE Sch.l of Excellence ',lookup_district_id('MONT', '17'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30208','Bamboo Town Public Sch. ',lookup_district_id('MONT', '17'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30210','30210 Millsburg Comm. Center ',lookup_district_id('MONT', '17'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30302','Pingi Town Arabic School ',lookup_district_id('MONT', '17'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30336','Gbondoi Public School ',lookup_district_id('MONT', '17'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30341','30341 Wesleyan School ',lookup_district_id('MONT', '17'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30342','Zunnah Town Public Sch. ',lookup_district_id('MONT', '17'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30343','A.G.M. Bible College ',lookup_district_id('MONT', '17'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30344','Madison Public School ',lookup_district_id('MONT', '17'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30345','Isaac Tondo Public Sch. ',lookup_district_id('MONT', '17'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30346','Old Triump Church Miss. ',lookup_district_id('MONT', '17'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30356','Kpallah Public School ',lookup_district_id('MONT', '17'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30357','Atherin School ',lookup_district_id('MONT', '17'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30358','Bamasee Public School ',lookup_district_id('MONT', '17'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30365','Ricks Institute ',lookup_district_id('MONT', '17'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30366','Billey Town Public School ',lookup_district_id('MONT', '17'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30367','Cheesemanburg Elem. & Jr. High School',lookup_district_id('MONT', '17'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30377','Lott Carey Mission School ',lookup_district_id('MONT', '17'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30391','Kubono Public School ',lookup_district_id('MONT', '17'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30418','Sawegbeh Public School ',lookup_district_id('MONT', '17'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30419','Kperkor Public School ',lookup_district_id('MONT', '17'),lookup_county_id('MONT'));
insert into precincts (code,name,district_id,county_id) values ('30420','Gandema Public School ',lookup_district_id('MONT', '17'),lookup_county_id('MONT'));


-- channels

insert into channels (name, phone, status) values ('Fake', '0000', 'A');
insert into channels (name, phone, status) values ('USA Nexmo', '+15152038684', 'A');


-- reporters

insert into reporters (name, phone, email) values ('Mlen-Too Wesley', '+13478789198', 'mlen.too.wesley@gmail.com');
insert into reporters (name, phone, email) values ('Lawrence Randall', '+231886400206', 'pellrandall@gmail.com');


-- elections

insert into elections (type, year, from_date, to_date) values ('S', 2014, '2014-12-01', '2014-12-31');


-- election channels

insert into election_channels (election_id, channel_id) values (lookup_election_id('S', 2014), lookup_channel_id(('0000')));
insert into election_channels (election_id, channel_id) values (lookup_election_id('S', 2014), lookup_channel_id('+15152038684'));


-- election reporters

insert into election_reporters (election_id, reporter_id, precinct_id) select lookup_election_id('S', 2014), lookup_reporter_id('+13478789198'), precincts.id from precincts;
insert into election_reporters (election_id, reporter_id, precinct_id) select lookup_election_id('S', 2014), lookup_reporter_id('+231886400206'), precincts.id from precincts;


-- election candidates

insert into election_candidates (election_id, candidate_id, precinct_id, party_id) select lookup_election_id('S', 2014), lookup_candidate_id('NATBL'), precincts.id, lookup_party_id('LINU') from precincts where precincts.county_id = lookup_county_id('MONT');
insert into election_candidates (election_id, candidate_id, precinct_id, party_id) select lookup_election_id('S', 2014), lookup_candidate_id('CECUF'), precincts.id, lookup_party_id('IND') from precincts where precincts.county_id = lookup_county_id('MONT');
insert into election_candidates (election_id, candidate_id, precinct_id, party_id) select lookup_election_id('S', 2014), lookup_candidate_id('MIAFA'), precincts.id, lookup_party_id('IND') from precincts where precincts.county_id = lookup_county_id('MONT');
insert into election_candidates (election_id, candidate_id, precinct_id, party_id) select lookup_election_id('S', 2014), lookup_candidate_id('JMFRE'), precincts.id, lookup_party_id('IND') from precincts where precincts.county_id = lookup_county_id('MONT');
insert into election_candidates (election_id, candidate_id, precinct_id, party_id) select lookup_election_id('S', 2014), lookup_candidate_id('SHAKO'), precincts.id, lookup_party_id('LTP') from precincts where precincts.county_id = lookup_county_id('MONT');
insert into election_candidates (election_id, candidate_id, precinct_id, party_id) select lookup_election_id('S', 2014), lookup_candidate_id('CHZNE'), precincts.id, lookup_party_id('IND') from precincts where precincts.county_id = lookup_county_id('MONT');
insert into election_candidates (election_id, candidate_id, precinct_id, party_id) select lookup_election_id('S', 2014), lookup_candidate_id('BERSA'), precincts.id, lookup_party_id('LP') from precincts where precincts.county_id = lookup_county_id('MONT');
insert into election_candidates (election_id, candidate_id, precinct_id, party_id) select lookup_election_id('S', 2014), lookup_candidate_id('ROASI'), precincts.id, lookup_party_id('IND') from precincts where precincts.county_id = lookup_county_id('MONT');
insert into election_candidates (election_id, candidate_id, precinct_id, party_id) select lookup_election_id('S', 2014), lookup_candidate_id('JALSU'), precincts.id, lookup_party_id('PUP') from precincts where precincts.county_id = lookup_county_id('MONT');
insert into election_candidates (election_id, candidate_id, precinct_id, party_id) select lookup_election_id('S', 2014), lookup_candidate_id('ALSYL'), precincts.id, lookup_party_id('UP') from precincts where precincts.county_id = lookup_county_id('MONT');
insert into election_candidates (election_id, candidate_id, precinct_id, party_id) select lookup_election_id('S', 2014), lookup_candidate_id('GEMWE'), precincts.id, lookup_party_id('CDC') from precincts where precincts.county_id = lookup_county_id('MONT');

